version: '3'

services:
  intelipostmiddleware.service:
    image: intelipostmiddlewareservice:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_intelipostmiddleware.service$
    volumes:
      - C:\Users\Leo\Desktop\job-integration-developer\IntelipostMiddleware:/app
      - C:\Users\Leo\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_intelipostmiddleware.service$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_intelipostmiddleware.service$ bin/Debug/netcoreapp2.0/IntelipostMiddleware.Service.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
